/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TablaRouteImport } from './routes/tabla'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnlinecoursesRouteImport } from './routes/onlinecourses'
import { Route as HindustaniClassicalRouteImport } from './routes/hindustani-classical'
import { Route as GuruPoornima2025RouteImport } from './routes/guru-poornima-2025'
import { Route as GuitarRouteImport } from './routes/guitar'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TablaRoute = TablaRouteImport.update({
  id: '/tabla',
  path: '/tabla',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlinecoursesRoute = OnlinecoursesRouteImport.update({
  id: '/onlinecourses',
  path: '/onlinecourses',
  getParentRoute: () => rootRouteImport,
} as any)
const HindustaniClassicalRoute = HindustaniClassicalRouteImport.update({
  id: '/hindustani-classical',
  path: '/hindustani-classical',
  getParentRoute: () => rootRouteImport,
} as any)
const GuruPoornima2025Route = GuruPoornima2025RouteImport.update({
  id: '/guru-poornima-2025',
  path: '/guru-poornima-2025',
  getParentRoute: () => rootRouteImport,
} as any)
const GuitarRoute = GuitarRouteImport.update({
  id: '/guitar',
  path: '/guitar',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certificates': typeof CertificatesRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/guitar': typeof GuitarRoute
  '/guru-poornima-2025': typeof GuruPoornima2025Route
  '/hindustani-classical': typeof HindustaniClassicalRoute
  '/onlinecourses': typeof OnlinecoursesRoute
  '/register': typeof RegisterRoute
  '/tabla': typeof TablaRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certificates': typeof CertificatesRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/guitar': typeof GuitarRoute
  '/guru-poornima-2025': typeof GuruPoornima2025Route
  '/hindustani-classical': typeof HindustaniClassicalRoute
  '/onlinecourses': typeof OnlinecoursesRoute
  '/register': typeof RegisterRoute
  '/tabla': typeof TablaRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certificates': typeof CertificatesRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/guitar': typeof GuitarRoute
  '/guru-poornima-2025': typeof GuruPoornima2025Route
  '/hindustani-classical': typeof HindustaniClassicalRoute
  '/onlinecourses': typeof OnlinecoursesRoute
  '/register': typeof RegisterRoute
  '/tabla': typeof TablaRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/certificates'
    | '/contact'
    | '/courses'
    | '/faqs'
    | '/gallery'
    | '/guitar'
    | '/guru-poornima-2025'
    | '/hindustani-classical'
    | '/onlinecourses'
    | '/register'
    | '/tabla'
    | '/thank-you'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/certificates'
    | '/contact'
    | '/courses'
    | '/faqs'
    | '/gallery'
    | '/guitar'
    | '/guru-poornima-2025'
    | '/hindustani-classical'
    | '/onlinecourses'
    | '/register'
    | '/tabla'
    | '/thank-you'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/certificates'
    | '/contact'
    | '/courses'
    | '/faqs'
    | '/gallery'
    | '/guitar'
    | '/guru-poornima-2025'
    | '/hindustani-classical'
    | '/onlinecourses'
    | '/register'
    | '/tabla'
    | '/thank-you'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CertificatesRoute: typeof CertificatesRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  FaqsRoute: typeof FaqsRoute
  GalleryRoute: typeof GalleryRoute
  GuitarRoute: typeof GuitarRoute
  GuruPoornima2025Route: typeof GuruPoornima2025Route
  HindustaniClassicalRoute: typeof HindustaniClassicalRoute
  OnlinecoursesRoute: typeof OnlinecoursesRoute
  RegisterRoute: typeof RegisterRoute
  TablaRoute: typeof TablaRoute
  ThankYouRoute: typeof ThankYouRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabla': {
      id: '/tabla'
      path: '/tabla'
      fullPath: '/tabla'
      preLoaderRoute: typeof TablaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onlinecourses': {
      id: '/onlinecourses'
      path: '/onlinecourses'
      fullPath: '/onlinecourses'
      preLoaderRoute: typeof OnlinecoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hindustani-classical': {
      id: '/hindustani-classical'
      path: '/hindustani-classical'
      fullPath: '/hindustani-classical'
      preLoaderRoute: typeof HindustaniClassicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guru-poornima-2025': {
      id: '/guru-poornima-2025'
      path: '/guru-poornima-2025'
      fullPath: '/guru-poornima-2025'
      preLoaderRoute: typeof GuruPoornima2025RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guitar': {
      id: '/guitar'
      path: '/guitar'
      fullPath: '/guitar'
      preLoaderRoute: typeof GuitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CertificatesRoute: CertificatesRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  FaqsRoute: FaqsRoute,
  GalleryRoute: GalleryRoute,
  GuitarRoute: GuitarRoute,
  GuruPoornima2025Route: GuruPoornima2025Route,
  HindustaniClassicalRoute: HindustaniClassicalRoute,
  OnlinecoursesRoute: OnlinecoursesRoute,
  RegisterRoute: RegisterRoute,
  TablaRoute: TablaRoute,
  ThankYouRoute: ThankYouRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
